/*
Prowlarr

Prowlarr API docs

API version: v1.13.3.4273
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package prowlarr

import (
	"encoding/json"
)

// DownloadClientConfigResource struct for DownloadClientConfigResource
type DownloadClientConfigResource struct {
	Id *int32 `json:"id,omitempty"`
}

// NewDownloadClientConfigResource instantiates a new DownloadClientConfigResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDownloadClientConfigResource() *DownloadClientConfigResource {
	this := DownloadClientConfigResource{}
	return &this
}

// NewDownloadClientConfigResourceWithDefaults instantiates a new DownloadClientConfigResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDownloadClientConfigResourceWithDefaults() *DownloadClientConfigResource {
	this := DownloadClientConfigResource{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DownloadClientConfigResource) GetId() int32 {
	if o == nil || isNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DownloadClientConfigResource) GetIdOk() (*int32, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DownloadClientConfigResource) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *DownloadClientConfigResource) SetId(v int32) {
	o.Id = &v
}

func (o DownloadClientConfigResource) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableDownloadClientConfigResource struct {
	value *DownloadClientConfigResource
	isSet bool
}

func (v NullableDownloadClientConfigResource) Get() *DownloadClientConfigResource {
	return v.value
}

func (v *NullableDownloadClientConfigResource) Set(val *DownloadClientConfigResource) {
	v.value = val
	v.isSet = true
}

func (v NullableDownloadClientConfigResource) IsSet() bool {
	return v.isSet
}

func (v *NullableDownloadClientConfigResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDownloadClientConfigResource(val *DownloadClientConfigResource) *NullableDownloadClientConfigResource {
	return &NullableDownloadClientConfigResource{value: val, isSet: true}
}

func (v NullableDownloadClientConfigResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDownloadClientConfigResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


