/*
Prowlarr

Prowlarr API docs

API version: v1.13.3.4273
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package prowlarr

import (
	"encoding/json"
)

// checks if the IndexerProxyResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndexerProxyResource{}

// IndexerProxyResource struct for IndexerProxyResource
type IndexerProxyResource struct {
	Id *int32 `json:"id,omitempty"`
	Name NullableString `json:"name,omitempty"`
	Fields []Field `json:"fields,omitempty"`
	ImplementationName NullableString `json:"implementationName,omitempty"`
	Implementation NullableString `json:"implementation,omitempty"`
	ConfigContract NullableString `json:"configContract,omitempty"`
	InfoLink NullableString `json:"infoLink,omitempty"`
	Message *ProviderMessage `json:"message,omitempty"`
	Tags []int32 `json:"tags,omitempty"`
	Presets []IndexerProxyResource `json:"presets,omitempty"`
	Link NullableString `json:"link,omitempty"`
	OnHealthIssue *bool `json:"onHealthIssue,omitempty"`
	SupportsOnHealthIssue *bool `json:"supportsOnHealthIssue,omitempty"`
	IncludeHealthWarnings *bool `json:"includeHealthWarnings,omitempty"`
	TestCommand NullableString `json:"testCommand,omitempty"`
}

// NewIndexerProxyResource instantiates a new IndexerProxyResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndexerProxyResource() *IndexerProxyResource {
	this := IndexerProxyResource{}
	return &this
}

// NewIndexerProxyResourceWithDefaults instantiates a new IndexerProxyResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndexerProxyResourceWithDefaults() *IndexerProxyResource {
	this := IndexerProxyResource{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IndexerProxyResource) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexerProxyResource) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IndexerProxyResource) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *IndexerProxyResource) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IndexerProxyResource) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IndexerProxyResource) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *IndexerProxyResource) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *IndexerProxyResource) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *IndexerProxyResource) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *IndexerProxyResource) UnsetName() {
	o.Name.Unset()
}

// GetFields returns the Fields field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IndexerProxyResource) GetFields() []Field {
	if o == nil {
		var ret []Field
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IndexerProxyResource) GetFieldsOk() ([]Field, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *IndexerProxyResource) HasFields() bool {
	if o != nil && IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []Field and assigns it to the Fields field.
func (o *IndexerProxyResource) SetFields(v []Field) {
	o.Fields = v
}

// GetImplementationName returns the ImplementationName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IndexerProxyResource) GetImplementationName() string {
	if o == nil || IsNil(o.ImplementationName.Get()) {
		var ret string
		return ret
	}
	return *o.ImplementationName.Get()
}

// GetImplementationNameOk returns a tuple with the ImplementationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IndexerProxyResource) GetImplementationNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ImplementationName.Get(), o.ImplementationName.IsSet()
}

// HasImplementationName returns a boolean if a field has been set.
func (o *IndexerProxyResource) HasImplementationName() bool {
	if o != nil && o.ImplementationName.IsSet() {
		return true
	}

	return false
}

// SetImplementationName gets a reference to the given NullableString and assigns it to the ImplementationName field.
func (o *IndexerProxyResource) SetImplementationName(v string) {
	o.ImplementationName.Set(&v)
}
// SetImplementationNameNil sets the value for ImplementationName to be an explicit nil
func (o *IndexerProxyResource) SetImplementationNameNil() {
	o.ImplementationName.Set(nil)
}

// UnsetImplementationName ensures that no value is present for ImplementationName, not even an explicit nil
func (o *IndexerProxyResource) UnsetImplementationName() {
	o.ImplementationName.Unset()
}

// GetImplementation returns the Implementation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IndexerProxyResource) GetImplementation() string {
	if o == nil || IsNil(o.Implementation.Get()) {
		var ret string
		return ret
	}
	return *o.Implementation.Get()
}

// GetImplementationOk returns a tuple with the Implementation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IndexerProxyResource) GetImplementationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Implementation.Get(), o.Implementation.IsSet()
}

// HasImplementation returns a boolean if a field has been set.
func (o *IndexerProxyResource) HasImplementation() bool {
	if o != nil && o.Implementation.IsSet() {
		return true
	}

	return false
}

// SetImplementation gets a reference to the given NullableString and assigns it to the Implementation field.
func (o *IndexerProxyResource) SetImplementation(v string) {
	o.Implementation.Set(&v)
}
// SetImplementationNil sets the value for Implementation to be an explicit nil
func (o *IndexerProxyResource) SetImplementationNil() {
	o.Implementation.Set(nil)
}

// UnsetImplementation ensures that no value is present for Implementation, not even an explicit nil
func (o *IndexerProxyResource) UnsetImplementation() {
	o.Implementation.Unset()
}

// GetConfigContract returns the ConfigContract field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IndexerProxyResource) GetConfigContract() string {
	if o == nil || IsNil(o.ConfigContract.Get()) {
		var ret string
		return ret
	}
	return *o.ConfigContract.Get()
}

// GetConfigContractOk returns a tuple with the ConfigContract field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IndexerProxyResource) GetConfigContractOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConfigContract.Get(), o.ConfigContract.IsSet()
}

// HasConfigContract returns a boolean if a field has been set.
func (o *IndexerProxyResource) HasConfigContract() bool {
	if o != nil && o.ConfigContract.IsSet() {
		return true
	}

	return false
}

// SetConfigContract gets a reference to the given NullableString and assigns it to the ConfigContract field.
func (o *IndexerProxyResource) SetConfigContract(v string) {
	o.ConfigContract.Set(&v)
}
// SetConfigContractNil sets the value for ConfigContract to be an explicit nil
func (o *IndexerProxyResource) SetConfigContractNil() {
	o.ConfigContract.Set(nil)
}

// UnsetConfigContract ensures that no value is present for ConfigContract, not even an explicit nil
func (o *IndexerProxyResource) UnsetConfigContract() {
	o.ConfigContract.Unset()
}

// GetInfoLink returns the InfoLink field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IndexerProxyResource) GetInfoLink() string {
	if o == nil || IsNil(o.InfoLink.Get()) {
		var ret string
		return ret
	}
	return *o.InfoLink.Get()
}

// GetInfoLinkOk returns a tuple with the InfoLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IndexerProxyResource) GetInfoLinkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InfoLink.Get(), o.InfoLink.IsSet()
}

// HasInfoLink returns a boolean if a field has been set.
func (o *IndexerProxyResource) HasInfoLink() bool {
	if o != nil && o.InfoLink.IsSet() {
		return true
	}

	return false
}

// SetInfoLink gets a reference to the given NullableString and assigns it to the InfoLink field.
func (o *IndexerProxyResource) SetInfoLink(v string) {
	o.InfoLink.Set(&v)
}
// SetInfoLinkNil sets the value for InfoLink to be an explicit nil
func (o *IndexerProxyResource) SetInfoLinkNil() {
	o.InfoLink.Set(nil)
}

// UnsetInfoLink ensures that no value is present for InfoLink, not even an explicit nil
func (o *IndexerProxyResource) UnsetInfoLink() {
	o.InfoLink.Unset()
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *IndexerProxyResource) GetMessage() ProviderMessage {
	if o == nil || IsNil(o.Message) {
		var ret ProviderMessage
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexerProxyResource) GetMessageOk() (*ProviderMessage, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *IndexerProxyResource) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given ProviderMessage and assigns it to the Message field.
func (o *IndexerProxyResource) SetMessage(v ProviderMessage) {
	o.Message = &v
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IndexerProxyResource) GetTags() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IndexerProxyResource) GetTagsOk() ([]int32, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *IndexerProxyResource) HasTags() bool {
	if o != nil && IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []int32 and assigns it to the Tags field.
func (o *IndexerProxyResource) SetTags(v []int32) {
	o.Tags = v
}

// GetPresets returns the Presets field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IndexerProxyResource) GetPresets() []IndexerProxyResource {
	if o == nil {
		var ret []IndexerProxyResource
		return ret
	}
	return o.Presets
}

// GetPresetsOk returns a tuple with the Presets field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IndexerProxyResource) GetPresetsOk() ([]IndexerProxyResource, bool) {
	if o == nil || IsNil(o.Presets) {
		return nil, false
	}
	return o.Presets, true
}

// HasPresets returns a boolean if a field has been set.
func (o *IndexerProxyResource) HasPresets() bool {
	if o != nil && IsNil(o.Presets) {
		return true
	}

	return false
}

// SetPresets gets a reference to the given []IndexerProxyResource and assigns it to the Presets field.
func (o *IndexerProxyResource) SetPresets(v []IndexerProxyResource) {
	o.Presets = v
}

// GetLink returns the Link field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IndexerProxyResource) GetLink() string {
	if o == nil || IsNil(o.Link.Get()) {
		var ret string
		return ret
	}
	return *o.Link.Get()
}

// GetLinkOk returns a tuple with the Link field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IndexerProxyResource) GetLinkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Link.Get(), o.Link.IsSet()
}

// HasLink returns a boolean if a field has been set.
func (o *IndexerProxyResource) HasLink() bool {
	if o != nil && o.Link.IsSet() {
		return true
	}

	return false
}

// SetLink gets a reference to the given NullableString and assigns it to the Link field.
func (o *IndexerProxyResource) SetLink(v string) {
	o.Link.Set(&v)
}
// SetLinkNil sets the value for Link to be an explicit nil
func (o *IndexerProxyResource) SetLinkNil() {
	o.Link.Set(nil)
}

// UnsetLink ensures that no value is present for Link, not even an explicit nil
func (o *IndexerProxyResource) UnsetLink() {
	o.Link.Unset()
}

// GetOnHealthIssue returns the OnHealthIssue field value if set, zero value otherwise.
func (o *IndexerProxyResource) GetOnHealthIssue() bool {
	if o == nil || IsNil(o.OnHealthIssue) {
		var ret bool
		return ret
	}
	return *o.OnHealthIssue
}

// GetOnHealthIssueOk returns a tuple with the OnHealthIssue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexerProxyResource) GetOnHealthIssueOk() (*bool, bool) {
	if o == nil || IsNil(o.OnHealthIssue) {
		return nil, false
	}
	return o.OnHealthIssue, true
}

// HasOnHealthIssue returns a boolean if a field has been set.
func (o *IndexerProxyResource) HasOnHealthIssue() bool {
	if o != nil && !IsNil(o.OnHealthIssue) {
		return true
	}

	return false
}

// SetOnHealthIssue gets a reference to the given bool and assigns it to the OnHealthIssue field.
func (o *IndexerProxyResource) SetOnHealthIssue(v bool) {
	o.OnHealthIssue = &v
}

// GetSupportsOnHealthIssue returns the SupportsOnHealthIssue field value if set, zero value otherwise.
func (o *IndexerProxyResource) GetSupportsOnHealthIssue() bool {
	if o == nil || IsNil(o.SupportsOnHealthIssue) {
		var ret bool
		return ret
	}
	return *o.SupportsOnHealthIssue
}

// GetSupportsOnHealthIssueOk returns a tuple with the SupportsOnHealthIssue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexerProxyResource) GetSupportsOnHealthIssueOk() (*bool, bool) {
	if o == nil || IsNil(o.SupportsOnHealthIssue) {
		return nil, false
	}
	return o.SupportsOnHealthIssue, true
}

// HasSupportsOnHealthIssue returns a boolean if a field has been set.
func (o *IndexerProxyResource) HasSupportsOnHealthIssue() bool {
	if o != nil && !IsNil(o.SupportsOnHealthIssue) {
		return true
	}

	return false
}

// SetSupportsOnHealthIssue gets a reference to the given bool and assigns it to the SupportsOnHealthIssue field.
func (o *IndexerProxyResource) SetSupportsOnHealthIssue(v bool) {
	o.SupportsOnHealthIssue = &v
}

// GetIncludeHealthWarnings returns the IncludeHealthWarnings field value if set, zero value otherwise.
func (o *IndexerProxyResource) GetIncludeHealthWarnings() bool {
	if o == nil || IsNil(o.IncludeHealthWarnings) {
		var ret bool
		return ret
	}
	return *o.IncludeHealthWarnings
}

// GetIncludeHealthWarningsOk returns a tuple with the IncludeHealthWarnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndexerProxyResource) GetIncludeHealthWarningsOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeHealthWarnings) {
		return nil, false
	}
	return o.IncludeHealthWarnings, true
}

// HasIncludeHealthWarnings returns a boolean if a field has been set.
func (o *IndexerProxyResource) HasIncludeHealthWarnings() bool {
	if o != nil && !IsNil(o.IncludeHealthWarnings) {
		return true
	}

	return false
}

// SetIncludeHealthWarnings gets a reference to the given bool and assigns it to the IncludeHealthWarnings field.
func (o *IndexerProxyResource) SetIncludeHealthWarnings(v bool) {
	o.IncludeHealthWarnings = &v
}

// GetTestCommand returns the TestCommand field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IndexerProxyResource) GetTestCommand() string {
	if o == nil || IsNil(o.TestCommand.Get()) {
		var ret string
		return ret
	}
	return *o.TestCommand.Get()
}

// GetTestCommandOk returns a tuple with the TestCommand field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IndexerProxyResource) GetTestCommandOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TestCommand.Get(), o.TestCommand.IsSet()
}

// HasTestCommand returns a boolean if a field has been set.
func (o *IndexerProxyResource) HasTestCommand() bool {
	if o != nil && o.TestCommand.IsSet() {
		return true
	}

	return false
}

// SetTestCommand gets a reference to the given NullableString and assigns it to the TestCommand field.
func (o *IndexerProxyResource) SetTestCommand(v string) {
	o.TestCommand.Set(&v)
}
// SetTestCommandNil sets the value for TestCommand to be an explicit nil
func (o *IndexerProxyResource) SetTestCommandNil() {
	o.TestCommand.Set(nil)
}

// UnsetTestCommand ensures that no value is present for TestCommand, not even an explicit nil
func (o *IndexerProxyResource) UnsetTestCommand() {
	o.TestCommand.Unset()
}

func (o IndexerProxyResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndexerProxyResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Fields != nil {
		toSerialize["fields"] = o.Fields
	}
	if o.ImplementationName.IsSet() {
		toSerialize["implementationName"] = o.ImplementationName.Get()
	}
	if o.Implementation.IsSet() {
		toSerialize["implementation"] = o.Implementation.Get()
	}
	if o.ConfigContract.IsSet() {
		toSerialize["configContract"] = o.ConfigContract.Get()
	}
	if o.InfoLink.IsSet() {
		toSerialize["infoLink"] = o.InfoLink.Get()
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.Presets != nil {
		toSerialize["presets"] = o.Presets
	}
	if o.Link.IsSet() {
		toSerialize["link"] = o.Link.Get()
	}
	if !IsNil(o.OnHealthIssue) {
		toSerialize["onHealthIssue"] = o.OnHealthIssue
	}
	if !IsNil(o.SupportsOnHealthIssue) {
		toSerialize["supportsOnHealthIssue"] = o.SupportsOnHealthIssue
	}
	if !IsNil(o.IncludeHealthWarnings) {
		toSerialize["includeHealthWarnings"] = o.IncludeHealthWarnings
	}
	if o.TestCommand.IsSet() {
		toSerialize["testCommand"] = o.TestCommand.Get()
	}
	return toSerialize, nil
}

type NullableIndexerProxyResource struct {
	value *IndexerProxyResource
	isSet bool
}

func (v NullableIndexerProxyResource) Get() *IndexerProxyResource {
	return v.value
}

func (v *NullableIndexerProxyResource) Set(val *IndexerProxyResource) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexerProxyResource) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexerProxyResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexerProxyResource(val *IndexerProxyResource) *NullableIndexerProxyResource {
	return &NullableIndexerProxyResource{value: val, isSet: true}
}

func (v NullableIndexerProxyResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexerProxyResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


